# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10cb92410cd0aca831d0b9489e5f934d005c68fdfa8eccf51d096d8c0a2daf94ff3df9b9c1863c418fef58df450c3531333cc32b455d50985c408dad6cc3a8fa
  api_token: j6hd9@l664HDv2agh
  
test:
  secret_key_base: 46b0af7a7c117699c3b499cd8039ff0585cf1927453afd64f6a38e7b16f74992f9894d46a9765ade8bbba759a18f8ed166dc7c90b3ae9195374c08692ee0a0d5
  api_token: j6hd9@l664HDv2agh

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token: j6hd9@l664HDv2agh
